'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Bot, Building2, CalendarClock, CreditCard, FileText, ShieldCheck, Users, Wallet } from 'lucide-react';
import { getMerchantOwnerProfile } from '@/app/actions/superadmin';

const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString('ar-EG', { dateStyle: 'medium', timeStyle: 'short' }) : '—';

export default function MerchantOwnerProfile({ tenantId }: { tenantId: string }) {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  useEffect(() => { void getMerchantOwnerProfile(tenantId).then((result) => result.success ? setData(result) : setError(result.error || 'تعذر تحميل ملف التاجر.')); }, [tenantId]);
  if (error) return <main dir="rtl" className="min-h-dvh bg-zinc-950 p-6 text-zinc-100"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-black text-emerald-300"><ArrowRight className="h-4 w-4" />العودة للمالك</Link><p className="mt-8 rounded-2xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-100">{error}</p></main>;
  if (!data) return <main className="min-h-dvh bg-zinc-950 p-6"><div className="mx-auto max-w-6xl space-y-4"><div className="h-10 w-40 animate-pulse rounded-xl bg-zinc-800" /><div className="h-60 animate-pulse rounded-2xl bg-zinc-900" /></div></main>;
  const merchant = data.merchant;
  const tile = (label: string, value: string | number, icon: React.ReactNode) => <div className="rounded-2xl border border-zinc-800 bg-zinc-900/45 p-4"><div className="flex items-center justify-between text-zinc-300">{icon}<span className="text-xs font-bold">{label}</span></div><p className="mt-4 text-2xl font-black tabular-nums text-white">{value}</p></div>;
  return <main dir="rtl" className="min-h-dvh bg-zinc-950 pb-12 text-zinc-100"><div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><Link href="/admin" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-zinc-700 px-3 text-sm font-black text-zinc-100 transition-colors hover:bg-zinc-900"><ArrowRight className="h-4 w-4" />العودة للوحة المالك</Link>
    <header className="mt-6 border-b border-zinc-800 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-black text-white">{merchant.storeName}</h1><p className="mt-2 text-sm text-zinc-300">ملف موحد للتاجر: الاشتراك، النشاط، العملاء، الفوترة والسجل التشغيلي.</p></div><span className={merchant.saasStatus === 'active' ? 'rounded-full bg-emerald-500/15 px-3 py-1.5 text-xs font-black text-emerald-200' : 'rounded-full bg-rose-500/15 px-3 py-1.5 text-xs font-black text-rose-100'}>{merchant.saasStatus === 'active' ? 'اشتراك المنصة نشط' : 'اشتراك المنصة غير نشط'}</span></div></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tile('رصيد المنصة', `${Number(merchant.saasBalance).toFixed(2)} EGP`, <Wallet className="h-5 w-5 text-emerald-300" />)}{tile('العملاء', merchant._count.customers, <Users className="h-5 w-5 text-sky-300" />)}{tile('الاشتراكات', merchant._count.subscriptions, <CalendarClock className="h-5 w-5 text-amber-200" />)}{tile('طلبات التنفيذ', merchant._count.orders, <FileText className="h-5 w-5 text-amber-200" />)}</section>
    <section className="mt-6 grid gap-5 lg:grid-cols-3"><div className="lg:col-span-2 space-y-5"><article className="rounded-2xl border border-zinc-800 bg-zinc-900/35 p-5"><h2 className="flex items-center gap-2 text-base font-black text-white"><Building2 className="h-5 w-5 text-emerald-300" />بيانات المتجر والحساب</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-zinc-400">الباقة</dt><dd className="mt-1 font-bold text-white">{merchant.saasPlan}</dd></div><div><dt className="text-zinc-400">ينتهي في</dt><dd className="mt-1 font-bold text-white">{date(merchant.saasExpiry)}</dd></div><div><dt className="text-zinc-400">التجديد التلقائي</dt><dd className="mt-1 font-bold text-white">{merchant.autoRenew ? 'مفعل' : 'غير مفعل'}</dd></div><div><dt className="text-zinc-400">البوت</dt><dd className="mt-1 font-bold text-white">{merchant.botSettings?.botUsername ? `@${merchant.botSettings.botUsername} — ${merchant.botSettings.connectionStatus}` : 'لم يتم ربط بوت'}</dd></div></dl><div className="mt-5 border-t border-zinc-800 pt-4"><p className="text-xs font-bold text-zinc-400">الحسابات الإدارية</p><div className="mt-3 divide-y divide-zinc-800 rounded-xl border border-zinc-800">{merchant.users.map((user: any) => <div key={user.id} className="flex items-center justify-between gap-4 px-3 py-3 text-sm"><div><p className="font-bold text-zinc-100">{user.fullName || user.username}</p><p className="mt-1 text-xs text-zinc-400">@{user.username} · {user.role}</p></div><span className={user.isActive ? 'text-xs font-bold text-emerald-300' : 'text-xs font-bold text-rose-200'}>{user.isActive ? 'نشط' : 'موقوف'}</span></div>)}</div></div></article>
      <article className="rounded-2xl border border-zinc-800 bg-zinc-900/35 p-5"><h2 className="flex items-center gap-2 text-base font-black text-white"><CreditCard className="h-5 w-5 text-sky-300" />الفواتير وطلبات الشحن</h2><div className="mt-4 overflow-x-auto"><table className="min-w-[600px] w-full text-right text-xs"><thead className="border-b border-zinc-800 text-zinc-400"><tr><th className="pb-3">الرقم</th><th className="pb-3">المبلغ</th><th className="pb-3">الحالة</th><th className="pb-3">التاريخ</th></tr></thead><tbody className="divide-y divide-zinc-800">{data.invoices.map((invoice: any) => <tr key={invoice.id}><td className="py-3 font-bold text-zinc-100">{invoice.number}</td><td className="py-3 text-emerald-300">{Number(invoice.amount).toFixed(2)} {invoice.currency}</td><td className="py-3 text-zinc-300">{invoice.status}</td><td className="py-3 text-zinc-400">{date(invoice.paidAt || invoice.createdAt)}</td></tr>)}{!data.invoices.length ? <tr><td colSpan={4} className="py-5 text-center text-zinc-400">لا توجد فواتير بعد.</td></tr> : null}</tbody></table></div></article>
      <article className="rounded-2xl border border-zinc-800 bg-zinc-900/35 p-5"><h2 className="flex items-center gap-2 text-base font-black text-white"><ShieldCheck className="h-5 w-5 text-amber-200" />آخر نشاط مسجل</h2><div className="mt-4 divide-y divide-zinc-800">{data.auditLogs.map((log: any) => <div key={log.id} className="py-3 text-sm"><p className="font-bold text-zinc-100">{log.action}</p><p className="mt-1 text-xs text-zinc-400">{log.user?.username || 'النظام'} · {date(log.createdAt)}</p></div>)}{!data.auditLogs.length ? <p className="py-5 text-sm text-zinc-400">لا توجد سجلات بعد.</p> : null}</div></article></div>
      <aside className="space-y-5"><article className="rounded-2xl border border-zinc-800 bg-zinc-900/35 p-5"><h2 className="text-base font-black text-white">إحالة التاجر</h2>{merchant.referralProgram ? <div className="mt-4 space-y-3 text-sm"><p className="rounded-xl bg-zinc-950/65 p-3 font-mono text-xs text-zinc-100">{merchant.referralProgram.code}</p><p className="text-zinc-300">النسبة: <b className="text-emerald-300">{Number(merchant.referralProgram.commissionRate).toFixed(0)}%</b></p><p className="text-zinc-300">المدعوون: <b className="text-white">{merchant.referralProgram._count.attributions}</b></p><p className="text-zinc-300">الرصيد المتاح: <b className="text-white">{Number(merchant.referralProgram.availableBalance).toFixed(2)} EGP</b></p><p className="text-zinc-300">طلبات السحب: <b className="text-white">{merchant.referralProgram._count.payoutRequests}</b></p></div> : <p className="mt-3 text-sm text-zinc-400">سيُنشأ برنامج الإحالة عند أول فتح للتاجر لمركز الإحالة.</p>}</article><article className="rounded-2xl border border-zinc-800 bg-zinc-900/35 p-5"><h2 className="text-base font-black text-white">وسائل التواصل والدفع</h2><div className="mt-4 space-y-3 text-sm">{merchant.contacts.map((item: any, index: number) => <p key={`${item.type}-${index}`} className="text-zinc-300"><b className="text-white">{item.label}:</b> {item.value}</p>)}{merchant.paymentMethods.map((item: any, index: number) => <p key={`${item.type}-${index}`} className="text-zinc-300"><b className="text-white">{item.label}:</b> {item.accountIdentifier}</p>)}{!merchant.contacts.length && !merchant.paymentMethods.length ? <p className="text-zinc-400">لم يضف التاجر هذه البيانات بعد.</p> : null}</div></article></aside></section>
  </div></main>;
}
