'use client';

import { FormEvent, useEffect, useState, useTransition } from 'react';
import { deleteMessageTemplate, getMessageTemplates, saveMessageTemplate } from '@/app/actions/message-templates';

export default function MessagesPage() {
  const [items, setItems] = useState<any[]>([]); const [notice, setNotice] = useState(''); const [pending, startTransition] = useTransition();
  const [form, setForm] = useState({ name: '', category: 'عام', channel: 'telegram', content: 'مرحبًا {customer_name}' });
  const refresh = async () => { const data = await getMessageTemplates(); if (data.success) setItems(data.templates); };
  useEffect(() => { void refresh(); }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); startTransition(async () => { try { await saveMessageTemplate(form); setForm({ name: '', category: 'عام', channel: 'telegram', content: 'مرحبًا {customer_name}' }); setNotice('تم حفظ القالب.'); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : 'تعذر الحفظ.'); } }); };
  return <main className="space-y-6" dir="rtl"><header><p className="text-sm text-emerald-400">التواصل والأتمتة</p><h1 className="mt-1 text-2xl font-bold text-white">قوالب الرسائل</h1><p className="mt-2 text-sm text-zinc-400">أنشئ رسالة مرة واحدة واستخدم متغيرات مثل <span className="text-zinc-200">{'{customer_name}'}</span> و{'{service_name}'} عند المتابعة.</p></header><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={submit} className="space-y-3 rounded-2xl border border-white/10 bg-zinc-950/60 p-5"><h2 className="font-bold text-white">قالب جديد</h2><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black px-3 py-2.5 text-sm text-white" placeholder="اسم القالب"/><div className="grid grid-cols-2 gap-2"><input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="rounded-xl border border-white/10 bg-black px-3 py-2.5 text-sm text-white" placeholder="التصنيف"/><select value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value })} className="rounded-xl border border-white/10 bg-black px-3 py-2.5 text-sm text-white"><option value="telegram">تيليجرام</option><option value="whatsapp">واتساب</option><option value="internal">داخلي</option></select></div><textarea value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} className="min-h-36 w-full rounded-xl border border-white/10 bg-black px-3 py-2.5 text-sm text-white"/><button disabled={pending} className="w-full rounded-xl bg-emerald-500 py-2.5 text-sm font-bold text-black">{pending ? 'جارٍ الحفظ…' : 'حفظ القالب'}</button>{notice ? <p className="text-xs text-emerald-300">{notice}</p> : null}</form><section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950/60"><div className="border-b border-white/10 px-5 py-4 font-bold text-white">القوالب المحفوظة</div>{items.length ? items.map((item) => <article key={item.id} className="border-b border-white/5 px-5 py-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-white">{item.name}</p><p className="mt-1 text-xs text-zinc-500">{item.category} · {item.channel}</p></div><button onClick={() => startTransition(async () => { await deleteMessageTemplate(item.id); await refresh(); })} className="text-xs text-rose-300">حذف</button></div><p className="mt-3 whitespace-pre-wrap text-sm text-zinc-300">{item.content}</p></article>) : <p className="p-10 text-center text-sm text-zinc-500">لا توجد قوالب بعد.</p>}</section></div></main>;
}
