'use client';

import { useEffect, useState } from 'react';
import { getExecutiveOverview } from '@/app/actions/executive-overview';

export default function ExecutiveOverview() {
  const [data, setData] = useState<any>(null);
  useEffect(() => { void getExecutiveOverview().then((result) => { if (result.success) setData(result); }).catch(() => undefined); }, []);
  if (!data) return <section className="mt-7 grid animate-pulse gap-4 lg:grid-cols-3"><div className="h-72 rounded-2xl bg-zinc-900" /><div className="h-72 rounded-2xl bg-zinc-900 lg:col-span-2" /></section>;
  const max = Math.max(1, ...data.months.flatMap((item: any) => [item.revenue, item.profit])); const current = data.months.at(-1);
  return <section className="mt-7 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="إيراد هذا الشهر" value={current.revenue} currency={data.currency} /><Metric label="صافي ربح هذا الشهر" value={current.profit} currency={data.currency} positive /><Metric label="مصروفات هذا الشهر" value={current.expenses} currency={data.currency} /></div><div className="grid gap-4 lg:grid-cols-[1.65fr_.85fr]"><section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><div className="flex items-start justify-between"><div><h2 className="font-black text-white">اتجاه الإيراد والربح</h2><p className="mt-1 text-sm text-zinc-500">آخر 6 أشهر من البيانات الفعلية</p></div><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-bold text-emerald-300">{data.currency}</span></div><div className="mt-6 flex h-48 items-end gap-3">{data.months.map((month: any) => <div key={month.key} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-40 w-full items-end justify-center gap-1.5"><span className="w-[42%] rounded-t-md bg-emerald-400/85" style={{ height: `${Math.max(4, month.revenue / max * 100)}%` }} /><span className="w-[42%] rounded-t-md bg-violet-400/85" style={{ height: `${Math.max(4, Math.max(0, month.profit) / max * 100)}%` }} /></div><span className="text-[11px] text-zinc-500">{month.label}</span></div>)}</div><div className="mt-4 flex gap-4 text-xs text-zinc-400"><span><i className="ml-1 inline-block h-2 w-2 rounded-sm bg-emerald-400" />الإيراد</span><span><i className="ml-1 inline-block h-2 w-2 rounded-sm bg-violet-400" />صافي الربح</span></div></section><section className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><h2 className="font-black text-white">أقوى الخدمات</h2><p className="mt-1 text-sm text-zinc-500">بحسب المبيعات خلال الفترة</p><div className="mt-5 space-y-4">{data.topServices.length ? data.topServices.map((service: any, index: number) => <div key={service.name}><div className="flex justify-between gap-3 text-sm"><span className="truncate text-zinc-200">{index + 1}. {service.name}</span><span className="font-bold text-emerald-300">{Number(service.revenue).toLocaleString('ar-EG')}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${service.revenue / data.topServices[0].revenue * 100}%` }} /></div></div>) : <p className="py-12 text-center text-sm text-zinc-500">لا توجد مبيعات كافية للرسم.</p>}</div></section></div></section>;
}

function Metric({ label, value, currency, positive }: { label: string; value: number; currency: string; positive?: boolean }) { return <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4"><p className="text-xs text-zinc-500">{label}</p><p className={`mt-3 text-2xl font-black ${positive ? 'text-emerald-300' : 'text-white'}`}>{Number(value).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} <span className="text-sm text-zinc-500">{currency}</span></p></div>; }
