'use client';

import { FormEvent, useEffect, useState, useTransition } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowLeft, Pencil, RefreshCw, Search, X } from 'lucide-react';
import { getCustomers, updateCustomer } from '@/app/actions/merchant';

type Customer = { id: string; name: string; phone: string; email?: string | null; company?: string | null; notes?: string | null; stage: string; source?: string | null; tags: string[]; walletBalance: number; _count?: { subscriptions: number; tasks: number; deals: number } };
const empty = { name: '', phone: '', email: '', company: '', notes: '', stage: 'customer', source: '', tags: '' };
const inputClass = 'w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3.5 py-3 text-sm font-semibold text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-emerald-500/70';

export default function CustomersPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const legacyCustomerId = searchParams.get('customerId');
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<Customer | null>(null);
  const [form, setForm] = useState(empty);
  const [notice, setNotice] = useState('');
  const [loading, setLoading] = useState(true);
  const [pending, startTransition] = useTransition();

  useEffect(() => { if (legacyCustomerId) router.replace(`/dashboard/customers/${legacyCustomerId}`); }, [legacyCustomerId, router]);
  const refresh = async () => {
    setLoading(true);
    const result = await getCustomers({ search: query, pageSize: 100 });
    if (result.success) setCustomers(result.customers as Customer[]); else setNotice(result.error || 'تعذر جلب العملاء.');
    setLoading(false);
  };
  useEffect(() => { if (!legacyCustomerId) void refresh(); }, [legacyCustomerId]);
  const begin = (customer: Customer) => { setEditing(customer); setForm({ name: customer.name, phone: customer.phone, email: customer.email || '', company: customer.company || '', notes: customer.notes || '', stage: customer.stage, source: customer.source || '', tags: customer.tags.join(', ') }); };
  const save = (event: FormEvent) => { event.preventDefault(); if (!editing) return; startTransition(async () => { const result = await updateCustomer(editing.id, { ...form, tags: form.tags.split(',').map((item) => item.trim()).filter(Boolean) }); if (result.success) { setNotice('تم حفظ بيانات العميل.'); setEditing(null); await refresh(); } else setNotice(result.error || 'تعذر حفظ البيانات.'); }); };

  if (legacyCustomerId) return <main className="grid min-h-64 place-items-center" dir="rtl"><p className="rounded-xl border border-zinc-800 bg-zinc-900 px-5 py-4 text-sm font-bold text-zinc-300">جارٍ فتح ملف العميل…</p></main>;

  return <main className="mx-auto max-w-7xl space-y-6 pb-12" dir="rtl">
    <header className="flex flex-col gap-4 border-b border-zinc-800 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight text-white">العملاء</h1><p className="mt-2 text-sm font-medium text-zinc-400">افتح ملف كل عميل لمعرفة بياناته واشتراكاته ومدفوعاته وسجل المتابعة كاملًا.</p></div><form onSubmit={(event) => { event.preventDefault(); void refresh(); }} className="flex w-full gap-2 sm:w-auto"><label className="relative flex-1 sm:w-80"><Search className="absolute right-3 top-3.5 h-4 w-4 text-zinc-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} className={`${inputClass} pr-10`} placeholder="ابحث بالاسم أو الرقم" /></label><button className="rounded-xl bg-emerald-500 px-4 py-3 text-sm font-black text-zinc-950 hover:bg-emerald-400">بحث</button><button type="button" onClick={() => void refresh()} aria-label="تحديث العملاء" className="rounded-xl border border-zinc-700 px-3 text-zinc-300 hover:bg-zinc-800"><RefreshCw className="h-4 w-4" /></button></form></header>
    {notice ? <div className="flex items-center justify-between rounded-xl border border-emerald-500/25 bg-emerald-500/10 px-4 py-3 text-sm font-bold text-emerald-100"><span>{notice}</span><button onClick={() => setNotice('')} aria-label="إغلاق"><X className="h-4 w-4" /></button></div> : null}
    {loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3, 4, 5, 6].map((item) => <div key={item} className="h-48 animate-pulse rounded-2xl border border-zinc-800 bg-zinc-900/45" />)}</div> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.map((customer) => <article key={customer.id} className="flex min-h-52 flex-col rounded-2xl border border-zinc-800 bg-zinc-900/55 p-5 transition-colors hover:border-zinc-700"><div className="flex items-start justify-between gap-3"><Link href={`/dashboard/customers/${customer.id}`} className="flex min-w-0 items-start gap-3 rounded-lg outline-none focus-visible:ring-2 focus-visible:ring-emerald-400"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-500 font-black text-zinc-950">{customer.name.slice(0, 1)}</span><div className="min-w-0"><h2 className="truncate font-black text-white transition-colors hover:text-emerald-300">{customer.name}</h2><p dir="ltr" className="mt-1 text-sm text-zinc-500">{customer.phone}</p></div></Link><button onClick={() => begin(customer)} aria-label={`تعديل ${customer.name}`} className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-800 hover:text-white"><Pencil className="h-4 w-4" /></button></div><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-zinc-500">{customer.notes || 'لا توجد ملاحظات مسجلة.'}</p><div className="mt-4 flex flex-wrap gap-2 text-xs">{customer.tags.slice(0, 3).map((tag) => <span key={tag} className="rounded-full border border-zinc-700 bg-zinc-950 px-2.5 py-1 font-bold text-zinc-300">{tag}</span>)}<span className="rounded-full bg-zinc-800 px-2.5 py-1 font-bold text-zinc-300">{customer._count?.subscriptions || 0} اشتراك</span></div><Link href={`/dashboard/customers/${customer.id}`} className="mt-auto inline-flex items-center justify-between border-t border-zinc-800 pt-4 text-sm font-black text-emerald-300 hover:text-emerald-200"><span>فتح ملف العميل</span><ArrowLeft className="h-4 w-4" /></Link></article>)}{!customers.length ? <div className="col-span-full rounded-2xl border border-dashed border-zinc-700 px-5 py-14 text-center text-sm font-bold text-zinc-500">لا توجد نتائج مطابقة للبحث.</div> : null}</section>}
    {editing ? <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-3 backdrop-blur-sm sm:p-6" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setEditing(null); }}><form onSubmit={save} role="dialog" aria-modal="true" className="mx-auto my-4 w-full max-w-2xl rounded-2xl border border-zinc-700 bg-zinc-900 p-5 shadow-2xl shadow-black/50 sm:my-8 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">تعديل {editing.name}</h2><p className="mt-1 text-sm text-zinc-500">أو افتح ملف العميل لرؤية كل سجل التعاملات.</p></div><button type="button" onClick={() => setEditing(null)} aria-label="إغلاق" className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-800 hover:text-white"><X className="h-5 w-5" /></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={inputClass} placeholder="الاسم" /><input required dir="ltr" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className={inputClass} placeholder="الهاتف" /><input dir="ltr" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className={inputClass} placeholder="البريد الإلكتروني" /><input value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} className={inputClass} placeholder="الشركة" /></div><input value={form.tags} onChange={(event) => setForm({ ...form, tags: event.target.value })} className={`mt-3 ${inputClass}`} placeholder="وسوم مفصولة بفاصلة: مهم، تجديد" /><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} className={`mt-3 min-h-32 ${inputClass}`} placeholder="ملاحظات وتفاصيل المتابعة" /><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border border-zinc-700 px-4 py-3 text-sm font-bold text-zinc-200 hover:bg-zinc-800">إلغاء</button><button disabled={pending} className="rounded-xl bg-emerald-500 px-5 py-3 text-sm font-black text-zinc-950 hover:bg-emerald-400 disabled:opacity-50">{pending ? 'جارٍ الحفظ…' : 'حفظ التعديلات'}</button></div></form></div> : null}
  </main>;
}
